<Project Sdk="Microsoft.NET.Sdk.Worker">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Serilog.Extensions.Hosting" Version="8.0.0" />
    <PackageReference Include="Serilog.Settings.Configuration" Version="8.0.4" />
    <ProjectReference Include="../WAssis.Application/WAssis.Application.csproj" />
    <ProjectReference Include="../WAssis.Domain.Core/WAssis.Domain.Core.csproj" />
    <ProjectReference Include="../WAssis.Infra.CrossCutting.Bus/WAssis.Infra.CrossCutting.Bus.csproj" />
    <ProjectReference Include="../WAssis.Infra.CrossCutting.IoC/WAssis.Infra.CrossCutting.IoC.csproj" />
    <ProjectReference Include="../WAssis.Infra.Data/WAssis.Infra.Data.csproj" />
  </ItemGroup>
</Project>
