namespace WAssis.Services.Api.Modules.Customers.Contracts;

public sealed record UpdateInsuredPersonRequest(
    string? OfficeBranchId,
    string Name,
    string? PersonType,
    string? Status,
    string? DocumentNumber,
    string? Email,
    string? PhoneNumber,
    DateTime? BirthDateUtc,
    string? TradeName,
    string? Gender,
    string? MaritalStatus,
    string? CompanySize,
    string? Cnae,
    string? Website,
    string? PostalCode,
    string? Street,
    string? Number,
    string? Complement,
    string? Neighborhood,
    string? City,
    string? State,
    string? Notes,
    string? ProducerId,
    string? ManagerId,
    string? ChatwootId,
    bool? LgpdAuthorized,
    string? SocialName = null,
    string? IdentityDocument = null,
    string? MunicipalRegistration = null,
    string? EconomicActivity = null,
    string? Profession = null,
    decimal? MonthlyIncome = null,
    string? DriverLicenseNumber = null,
    string? DriverLicenseCategory = null,
    DateTime? DriverLicenseExpirationDate = null,
    string? MobilePhoneNumber = null,
    string? SecondaryPhoneNumber = null,
    string? WhatsAppNumber = null,
    string? Country = null,
    DateTime? LgpdAuthorizedAtUtc = null,
    string? ImportOrigin = null);
