using WAssis.Application.Abstractions.Messaging;
using WAssis.Application.Modules.Opportunities.Dtos;

namespace WAssis.Application.Modules.Opportunities.Commands;

public sealed record CreateOpportunityCommand(
    string? OfficeBranchId,
    string Name,
    string? ResponsibleId,
    Guid? InsuredPersonId,
    string? PipelineId,
    string? StageId,
    string? InsuranceLineId,
    string? InsurerId,
    string? OriginId,
    string? Status,
    string? BusinessType,
    bool? ContactType,
    decimal? NetPremium,
    decimal? CommissionPercentage,
    decimal? AgencyPercentage,
    DateTime? ValidityStartUtc,
    DateTime? ValidityEndUtc,
    DateTime? NextFollowUpUtc,
    string? Referrer,
    string? Notes,
    string? MetadataJson,
    Guid? OriginPolicyId = null,
    string? LeadName = null,
    string? LeadDocumentNumber = null,
    string? LeadEmail = null,
    string? LeadPhoneNumber = null,
    string? Title = null,
    string? Description = null,
    string? Priority = null,
    decimal? EstimatedPremiumAmount = null,
    decimal? EstimatedCommissionAmount = null,
    decimal? EstimatedCommissionPercentage = null,
    DateOnly? OpenedOn = null,
    DateOnly? ExpectedCloseDate = null,
    DateTime? WonAtUtc = null,
    DateTime? LostAtUtc = null,
    string? LossReasonNotes = null,
    string? Campaign = null,
    string? InternalNotes = null) : ICommand<OpportunityDto>;
