namespace WAssis.Services.Api.Modules.Quotes.Contracts;

public sealed record CreateQuoteRequestRequest(
    string? CorrelationId,
    string CustomerName,
    string DocumentNumber,
    string? Email,
    string? PhoneNumber,
    string? PostalCode,
    string? CustomerSurname,
    string? CustomerGender,
    string? CustomerMaritalStatusCode,
    DateTime? CustomerBirthDateUtc,
    int? DriverLicenseYears,
    string? DriverLicenseNumber,
    string? InsuredDriverRelationshipCode,
    string? VehicleChassisNumber,
    string? VehiclePlate,
    string? VehicleBrand,
    string? VehicleModel,
    string? VehicleFipeCode,
    int? VehicleManufactureYear,
    int VehicleModelYear,
    bool? VehicleIsZeroKm,
    bool? VehicleHasTracker,
    bool? VehicleHasAntiTheft,
    bool? VehicleIsFinanced,
    bool? VehicleIsArmored,
    string? VehicleFuelTypeCode,
    string? VehicleOvernightPostalCode,
    bool? VehicleHasKitGas,
    bool HasDriverUnder24,
    bool IsCurrentlyInsured,
    string? PreviousBonus,
    int? BrokerCommissionPercentage,
    int? RenewalInsurerCode,
    string? OfficeBranchId = null,
    Guid? OpportunityId = null,
    Guid? InsuranceBranchId = null,
    Guid? InsuredPersonId = null,
    string CalculationType = "AUTO",
    string CalculationOrigin = "PROPRIO",
    string? VersionLabel = null);
