<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Bcl.Memory" Version="10.0.7" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="8.0.0" />
    <ProjectReference Include="../WAssis.Application/WAssis.Application.csproj" />
    <ProjectReference Include="../WAssis.Domain/WAssis.Domain.csproj" />
    <ProjectReference Include="../WAssis.Domain.Core/WAssis.Domain.Core.csproj" />
    <ProjectReference Include="../WAssis.Infra.Data/WAssis.Infra.Data.csproj" />
    <ProjectReference Include="../WAssis.Infra.CrossCutting.Bus/WAssis.Infra.CrossCutting.Bus.csproj" />
    <ProjectReference Include="../WAssis.Infra.CrossCutting.Identity/WAssis.Infra.CrossCutting.Identity.csproj" />
  </ItemGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
</Project>
