<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="11.9.0" />
    <PackageReference Include="Serilog.AspNetCore" Version="8.0.3" />
    <PackageReference Include="Serilog.Settings.Configuration" Version="8.0.4" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.8.1" />
    <ProjectReference Include="../WAssis.Application/WAssis.Application.csproj" />
    <ProjectReference Include="../WAssis.Domain.Core/WAssis.Domain.Core.csproj" />
    <ProjectReference Include="../WAssis.Infra.Data/WAssis.Infra.Data.csproj" />
    <ProjectReference Include="../WAssis.Infra.CrossCutting.IoC/WAssis.Infra.CrossCutting.IoC.csproj" />
    <ProjectReference Include="../WAssis.Infra.CrossCutting.Identity/WAssis.Infra.CrossCutting.Identity.csproj" />
  </ItemGroup>
</Project>
